name: Building and Push to Docker Hub
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{  github.ref_name || "latest" }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/eth-wallet-gen:${{ env.IMAGE_TAG }}
