name: Code Analysis & Tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ["1.18.x", "1.x"]
    name: Lint, Test and Build (${{ matrix.os }}/${{ matrix.go-version }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Install dependencies
        run: go get ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --verbose

      - name: Test
        run: go test ./...

      - name: Build
        run: go build

      - name: Run
        run: go run main.go

      - name: Display Go version
        run: go version
